CREATE TABLE T (K INT, A INT, C CHAR(1), PRIMARY KEY(K));
INSERT INTO T VALUES(1,1,'A');
INSERT INTO T VALUES(2,1,'A');
INSERT INTO T VALUES(3,2,'A');
INSERT INTO T VALUES(4,3,'A');
INSERT INTO T VALUES(9,4,’A’);
INSERT INTO T VALUES(6,1,'B');
INSERT INTO T VALUES(7,1,'C');
INSERT INTO T VALUES(8,5,'a');
INSERT INTO T VALUES(9,6,'a');
SELECT * 
Quit;
